-- AP location id -> PopTracker section
-- Target: Pokemon Snap apworld 0.5.x (400 locations)
--
-- A 0.5.x seed may also generate "bonus" duplicates of random checks at
-- id + 1000, as filler slots. Both ids point at the same section, which
-- completes on whichever arrives first.
LOCATION_MAPPING = {

    -- Beach
    [7]    = {"@Butterfree/Picture"},                         -- Butterfree
    [1007] = {"@Butterfree/Picture"},                         -- Butterfree 2
    [9]    = {"@Pidgey/Picture"},                             -- Pidgey
    [1009] = {"@Pidgey/Picture"},                             -- Pidgey 2
    [10]   = {"@Pikachu/Beach Picture"},                      -- Pikachu (Beach)
    [1010] = {"@Pikachu/Beach Picture"},                      -- Pikachu (Beach) 2
    [19]   = {"@Meowth/Picture"},                             -- Meowth
    [1019] = {"@Meowth/Picture"},                             -- Meowth 2
    [34]   = {"@Doduo/Picture"},                              -- Doduo
    [1034] = {"@Doduo/Picture"},                              -- Doduo 2
    [42]   = {"@Chansey/Picture"},                            -- Chansey
    [1042] = {"@Chansey/Picture"},                            -- Chansey 2
    [43]   = {"@Kangaskhan/Picture"},                         -- Kangaskhan
    [1043] = {"@Kangaskhan/Picture"},                         -- Kangaskhan 2
    [47]   = {"@Scyther/Picture"},                            -- Scyther
    [1047] = {"@Scyther/Picture"},                            -- Scyther 2
    [51]   = {"@Magikarp/Beach Picture"},                     -- Magikarp (Beach)
    [1051] = {"@Magikarp/Beach Picture"},                     -- Magikarp (Beach) 2
    [53]   = {"@Lapras/Picture"},                             -- Lapras
    [1053] = {"@Lapras/Picture"},                             -- Lapras 2
    [55]   = {"@Eevee/Picture"},                              -- Eevee
    [1055] = {"@Eevee/Picture"},                              -- Eevee 2
    [57]   = {"@Snorlax/Picture"},                            -- Snorlax
    [1057] = {"@Snorlax/Picture"},                            -- Snorlax 2
    [107]  = {"@Butterfree/Wonderful Picture"},               -- Butterfree: Good Technique
    [1107] = {"@Butterfree/Wonderful Picture"},               -- Butterfree: Good Technique 2
    [109]  = {"@Pidgey/Wonderful Picture"},                   -- Pidgey: Good Technique
    [1109] = {"@Pidgey/Wonderful Picture"},                   -- Pidgey: Good Technique 2
    [110]  = {"@Pikachu/Beach Wonderful Picture"},            -- Pikachu (Beach): Good Technique
    [1110] = {"@Pikachu/Beach Wonderful Picture"},            -- Pikachu (Beach): Good Technique 2
    [119]  = {"@Meowth/Wonderful Picture"},                   -- Meowth: Good Technique
    [1119] = {"@Meowth/Wonderful Picture"},                   -- Meowth: Good Technique 2
    [134]  = {"@Doduo/Wonderful Picture"},                    -- Doduo: Good Technique
    [1134] = {"@Doduo/Wonderful Picture"},                    -- Doduo: Good Technique 2
    [142]  = {"@Chansey/Wonderful Picture"},                  -- Chansey: Good Technique
    [1142] = {"@Chansey/Wonderful Picture"},                  -- Chansey: Good Technique 2
    [143]  = {"@Kangaskhan/Wonderful Picture"},               -- Kangaskhan: Good Technique
    [1143] = {"@Kangaskhan/Wonderful Picture"},               -- Kangaskhan: Good Technique 2
    [147]  = {"@Scyther/Wonderful Picture"},                  -- Scyther: Good Technique
    [1147] = {"@Scyther/Wonderful Picture"},                  -- Scyther: Good Technique 2
    [151]  = {"@Magikarp/Beach Wonderful Picture"},           -- Magikarp (Beach): Good Technique
    [1151] = {"@Magikarp/Beach Wonderful Picture"},           -- Magikarp (Beach): Good Technique 2
    [153]  = {"@Lapras/Wonderful Picture"},                   -- Lapras: Good Technique
    [1153] = {"@Lapras/Wonderful Picture"},                   -- Lapras: Good Technique 2
    [155]  = {"@Eevee/Wonderful Picture"},                    -- Eevee: Good Technique
    [1155] = {"@Eevee/Wonderful Picture"},                    -- Eevee: Good Technique 2
    [157]  = {"@Snorlax/Wonderful Picture"},                  -- Snorlax: Good Technique
    [1157] = {"@Snorlax/Wonderful Picture"},                  -- Snorlax: Good Technique 2
    [207]  = {"@Butterfree/Same Pkmn"},                       -- Butterfree: Multiple
    [1207] = {"@Butterfree/Same Pkmn"},                       -- Butterfree: Multiple 2
    [209]  = {"@Pidgey/Same Pkmn"},                           -- Pidgey: Multiple
    [1209] = {"@Pidgey/Same Pkmn"},                           -- Pidgey: Multiple 2
    [210]  = {"@Pikachu/Same Pkmn"},                          -- Pikachu (Beach): Multiple
    [1210] = {"@Pikachu/Same Pkmn"},                          -- Pikachu (Beach): Multiple 2
    [253]  = {"@Lapras/Same Pkmn"},                           -- Lapras: Multiple
    [1253] = {"@Lapras/Same Pkmn"},                           -- Lapras: Multiple 2
    [301]  = {"@Pikachu/Surfing Pikachu"},                    -- Surfing Pikachu
    [1301] = {"@Pikachu/Surfing Pikachu"},                    -- Surfing Pikachu 2
    [305]  = {"@Pikachu/Pikachu on a Stump"},                 -- Pikachu on a Stump
    [1305] = {"@Pikachu/Pikachu on a Stump"},                 -- Pikachu on a Stump 2
    [307]  = {"@Pidgey/Gust-Using Pidgey"},                   -- Gust-Using Pidgey
    [1307] = {"@Pidgey/Gust-Using Pidgey"},                   -- Gust-Using Pidgey 2
    [400]  = {"@Beach/Pokemon Sign/Kingler Rock"},            -- Kingler Rock
    [1400] = {"@Beach/Pokemon Sign/Kingler Rock"},            -- Kingler Rock 2

    -- Tunnel
    [8]    = {"@Kakuna/Picture"},                             -- Kakuna
    [1008] = {"@Kakuna/Picture"},                             -- Kakuna 2
    [15]   = {"@Zubat/Tunnel Picture"},                       -- Zubat (Tunnel)
    [1015] = {"@Zubat/Tunnel Picture"},                       -- Zubat (Tunnel) 2
    [17]   = {"@Diglett/Picture"},                            -- Diglett
    [1017] = {"@Diglett/Picture"},                            -- Diglett 2
    [18]   = {"@Dugtrio/Picture"},                            -- Dugtrio
    [1018] = {"@Dugtrio/Picture"},                            -- Dugtrio 2
    [32]   = {"@Magnemite/Picture"},                          -- Magnemite
    [1032] = {"@Magnemite/Picture"},                          -- Magnemite 2
    [33]   = {"@Magneton/Picture"},                           -- Magneton
    [1033] = {"@Magneton/Picture"},                           -- Magneton 2
    [39]   = {"@Haunter/Picture"},                            -- Haunter
    [1039] = {"@Haunter/Picture"},                            -- Haunter 2
    [40]   = {"@Electrode/Picture"},                          -- Electrode
    [1040] = {"@Electrode/Picture"},                          -- Electrode 2
    [49]   = {"@Electabuzz/Picture"},                         -- Electabuzz
    [1049] = {"@Electabuzz/Picture"},                         -- Electabuzz 2
    [59]   = {"@Zapdos/Picture"},                             -- Zapdos
    [1059] = {"@Zapdos/Picture"},                             -- Zapdos 2
    [65]   = {"@Magikarp/Tunnel Picture"},                    -- Magikarp (Tunnel)
    [1065] = {"@Magikarp/Tunnel Picture"},                    -- Magikarp (Tunnel) 2
    [70]   = {"@Pikachu/Tunnel Picture"},                     -- Pikachu (Tunnel)
    [1070] = {"@Pikachu/Tunnel Picture"},                     -- Pikachu (Tunnel) 2
    [108]  = {"@Kakuna/Wonderful Picture"},                   -- Kakuna: Good Technique
    [1108] = {"@Kakuna/Wonderful Picture"},                   -- Kakuna: Good Technique 2
    [115]  = {"@Zubat/Tunnel Wonderful Picture"},             -- Zubat (Tunnel): Good Technique
    [1115] = {"@Zubat/Tunnel Wonderful Picture"},             -- Zubat (Tunnel): Good Technique 2
    [117]  = {"@Diglett/Wonderful Picture"},                  -- Diglett: Good Technique
    [1117] = {"@Diglett/Wonderful Picture"},                  -- Diglett: Good Technique 2
    [118]  = {"@Dugtrio/Wonderful Picture"},                  -- Dugtrio: Good Technique
    [1118] = {"@Dugtrio/Wonderful Picture"},                  -- Dugtrio: Good Technique 2
    [132]  = {"@Magnemite/Wonderful Picture"},                -- Magnemite: Good Technique
    [1132] = {"@Magnemite/Wonderful Picture"},                -- Magnemite: Good Technique 2
    [133]  = {"@Magneton/Wonderful Picture"},                 -- Magneton: Good Technique
    [1133] = {"@Magneton/Wonderful Picture"},                 -- Magneton: Good Technique 2
    [139]  = {"@Haunter/Wonderful Picture"},                  -- Haunter: Good Technique
    [1139] = {"@Haunter/Wonderful Picture"},                  -- Haunter: Good Technique 2
    [140]  = {"@Electrode/Wonderful Picture"},                -- Electrode: Good Technique
    [1140] = {"@Electrode/Wonderful Picture"},                -- Electrode: Good Technique 2
    [149]  = {"@Electabuzz/Wonderful Picture"},               -- Electabuzz: Good Technique
    [1149] = {"@Electabuzz/Wonderful Picture"},               -- Electabuzz: Good Technique 2
    [159]  = {"@Zapdos/Wonderful Picture"},                   -- Zapdos: Good Technique
    [1159] = {"@Zapdos/Wonderful Picture"},                   -- Zapdos: Good Technique 2
    [165]  = {"@Magikarp/Tunnel Wonderful Picture"},          -- Magikarp (Tunnel): Good Technique
    [1165] = {"@Magikarp/Tunnel Wonderful Picture"},          -- Magikarp (Tunnel): Good Technique 2
    [170]  = {"@Pikachu/Tunnel Wonderful Picture"},           -- Pikachu (Tunnel): Good Technique
    [1170] = {"@Pikachu/Tunnel Wonderful Picture"},           -- Pikachu (Tunnel): Good Technique 2
    [208]  = {"@Kakuna/Same Pkmn"},                           -- Kakuna: Multiple
    [1208] = {"@Kakuna/Same Pkmn"},                           -- Kakuna: Multiple 2
    [218]  = {"@Dugtrio/Same Pkmn"},                          -- Dugtrio: Multiple
    [1218] = {"@Dugtrio/Same Pkmn"},                          -- Dugtrio: Multiple 2
    [232]  = {"@Magnemite/Same Pkmn"},                        -- Magnemite: Multiple
    [1232] = {"@Magnemite/Same Pkmn"},                        -- Magnemite: Multiple 2
    [240]  = {"@Electrode/Same Pkmn"},                        -- Electrode: Multiple
    [1240] = {"@Electrode/Same Pkmn"},                        -- Electrode: Multiple 2
    [249]  = {"@Electabuzz/Same Pkmn"},                       -- Electabuzz: Multiple
    [1249] = {"@Electabuzz/Same Pkmn"},                       -- Electabuzz: Multiple 2
    [302]  = {"@Pikachu/Pikachu on a Ball"},                  -- Pikachu on a Ball
    [1302] = {"@Pikachu/Pikachu on a Ball"},                  -- Pikachu on a Ball 2
    [401]  = {"@Tunnel/Pokemon Sign/Pinsir Shadow"},          -- Pinsir's Shadow
    [1401] = {"@Tunnel/Pokemon Sign/Pinsir Shadow"},          -- Pinsir's Shadow 2
    [501]  = {"@Tunnel/Secret Exit/Tunnel"},                  -- Tunnel: Secret Exit
    [1501] = {"@Tunnel/Secret Exit/Tunnel"},                  -- Tunnel: Secret Exit 2

    -- Volcano
    [2]    = {"@Charmander/Picture"},                         -- Charmander
    [1002] = {"@Charmander/Picture"},                         -- Charmander 2
    [3]    = {"@Charmeleon/Picture"},                         -- Charmeleon
    [1003] = {"@Charmeleon/Picture"},                         -- Charmeleon 2
    [4]    = {"@Charizard/Picture"},                          -- Charizard
    [1004] = {"@Charizard/Picture"},                          -- Charizard 2
    [13]   = {"@Vulpix/Picture"},                             -- Vulpix
    [1013] = {"@Vulpix/Picture"},                             -- Vulpix 2
    [22]   = {"@Growlithe/Picture"},                          -- Growlithe
    [1022] = {"@Growlithe/Picture"},                          -- Growlithe 2
    [23]   = {"@Arcanine/Picture"},                           -- Arcanine
    [1023] = {"@Arcanine/Picture"},                           -- Arcanine 2
    [29]   = {"@Rapidash/Picture"},                           -- Rapidash
    [1029] = {"@Rapidash/Picture"},                           -- Rapidash 2
    [50]   = {"@Magmar/Picture"},                             -- Magmar
    [1050] = {"@Magmar/Picture"},                             -- Magmar 2
    [60]   = {"@Moltres/Picture"},                            -- Moltres
    [1060] = {"@Moltres/Picture"},                            -- Moltres 2
    [66]   = {"@Magikarp/Volcano Picture"},                   -- Magikarp (Volcano)
    [1066] = {"@Magikarp/Volcano Picture"},                   -- Magikarp (Volcano) 2
    [102]  = {"@Charmander/Wonderful Picture"},               -- Charmander: Good Technique
    [1102] = {"@Charmander/Wonderful Picture"},               -- Charmander: Good Technique 2
    [103]  = {"@Charmeleon/Wonderful Picture"},               -- Charmeleon: Good Technique
    [1103] = {"@Charmeleon/Wonderful Picture"},               -- Charmeleon: Good Technique 2
    [104]  = {"@Charizard/Wonderful Picture"},                -- Charizard: Good Technique
    [1104] = {"@Charizard/Wonderful Picture"},                -- Charizard: Good Technique 2
    [113]  = {"@Vulpix/Wonderful Picture"},                   -- Vulpix: Good Technique
    [1113] = {"@Vulpix/Wonderful Picture"},                   -- Vulpix: Good Technique 2
    [122]  = {"@Growlithe/Wonderful Picture"},                -- Growlithe: Good Technique
    [1122] = {"@Growlithe/Wonderful Picture"},                -- Growlithe: Good Technique 2
    [123]  = {"@Arcanine/Wonderful Picture"},                 -- Arcanine: Good Technique
    [1123] = {"@Arcanine/Wonderful Picture"},                 -- Arcanine: Good Technique 2
    [129]  = {"@Rapidash/Wonderful Picture"},                 -- Rapidash: Good Technique
    [1129] = {"@Rapidash/Wonderful Picture"},                 -- Rapidash: Good Technique 2
    [150]  = {"@Magmar/Wonderful Picture"},                   -- Magmar: Good Technique
    [1150] = {"@Magmar/Wonderful Picture"},                   -- Magmar: Good Technique 2
    [160]  = {"@Moltres/Wonderful Picture"},                  -- Moltres: Good Technique
    [1160] = {"@Moltres/Wonderful Picture"},                  -- Moltres: Good Technique 2
    [166]  = {"@Magikarp/Volcano Wonderful Picture"},         -- Magikarp (Volcano): Good Technique
    [1166] = {"@Magikarp/Volcano Wonderful Picture"},         -- Magikarp (Volcano): Good Technique 2
    [202]  = {"@Charmander/Same Pkmn"},                       -- Charmander: Multiple
    [1202] = {"@Charmander/Same Pkmn"},                       -- Charmander: Multiple 2
    [213]  = {"@Vulpix/Same Pkmn"},                           -- Vulpix: Multiple
    [1213] = {"@Vulpix/Same Pkmn"},                           -- Vulpix: Multiple 2
    [222]  = {"@Growlithe/Same Pkmn"},                        -- Growlithe: Multiple
    [1222] = {"@Growlithe/Same Pkmn"},                        -- Growlithe: Multiple 2
    [223]  = {"@Arcanine/Same Pkmn"},                         -- Arcanine: Multiple
    [1223] = {"@Arcanine/Same Pkmn"},                         -- Arcanine: Multiple 2
    [229]  = {"@Rapidash/Same Pkmn"},                         -- Rapidash: Multiple
    [1229] = {"@Rapidash/Same Pkmn"},                         -- Rapidash: Multiple 2
    [250]  = {"@Magmar/Same Pkmn"},                           -- Magmar: Multiple
    [1250] = {"@Magmar/Same Pkmn"},                           -- Magmar: Multiple 2
    [311]  = {"@Magmar/Fighting Magmar"},                     -- Fighting Magmar
    [1311] = {"@Magmar/Fighting Magmar"},                     -- Fighting Magmar 2
    [402]  = {"@Volcano/Pokemon Sign/Koffing Smoke"},         -- Koffing Smoke
    [1402] = {"@Volcano/Pokemon Sign/Koffing Smoke"},         -- Koffing Smoke 2

    -- River
    [1]    = {"@Bulbasaur/River Picture"},                    -- Bulbasaur (River)
    [1001] = {"@Bulbasaur/River Picture"},                    -- Bulbasaur (River) 2
    [6]    = {"@Metapod/Picture"},                            -- Metapod
    [1006] = {"@Metapod/Picture"},                            -- Metapod 2
    [16]   = {"@Vileplume/Picture"},                          -- Vileplume
    [1016] = {"@Vileplume/Picture"},                          -- Vileplume 2
    [20]   = {"@Psyduck/Picture"},                            -- Psyduck
    [1020] = {"@Psyduck/Picture"},                            -- Psyduck 2
    [24]   = {"@Poliwag/Picture"},                            -- Poliwag
    [1024] = {"@Poliwag/Picture"},                            -- Poliwag 2
    [30]   = {"@Slowpoke/Picture"},                           -- Slowpoke
    [1030] = {"@Slowpoke/Picture"},                           -- Slowpoke 2
    [31]   = {"@Slowbro/Picture"},                            -- Slowbro
    [1031] = {"@Slowbro/Picture"},                            -- Slowbro 2
    [37]   = {"@Shellder/Picture"},                           -- Shellder
    [1037] = {"@Shellder/Picture"},                           -- Shellder 2
    [38]   = {"@Cloyster/Picture"},                           -- Cloyster
    [1038] = {"@Cloyster/Picture"},                           -- Cloyster 2
    [56]   = {"@Porygon/Picture"},                            -- Porygon
    [1056] = {"@Porygon/Picture"},                            -- Porygon 2
    [67]   = {"@Magikarp/River Picture"},                     -- Magikarp (River)
    [1067] = {"@Magikarp/River Picture"},                     -- Magikarp (River) 2
    [71]   = {"@Pikachu/River Picture"},                      -- Pikachu (River)
    [1071] = {"@Pikachu/River Picture"},                      -- Pikachu (River) 2
    [101]  = {"@Bulbasaur/River Wonderful Picture"},          -- Bulbasaur (River): Good Technique
    [1101] = {"@Bulbasaur/River Wonderful Picture"},          -- Bulbasaur (River): Good Technique 2
    [106]  = {"@Metapod/Wonderful Picture"},                  -- Metapod: Good Technique
    [1106] = {"@Metapod/Wonderful Picture"},                  -- Metapod: Good Technique 2
    [116]  = {"@Vileplume/Wonderful Picture"},                -- Vileplume: Good Technique
    [1116] = {"@Vileplume/Wonderful Picture"},                -- Vileplume: Good Technique 2
    [120]  = {"@Psyduck/Wonderful Picture"},                  -- Psyduck: Good Technique
    [1120] = {"@Psyduck/Wonderful Picture"},                  -- Psyduck: Good Technique 2
    [124]  = {"@Poliwag/Wonderful Picture"},                  -- Poliwag: Good Technique
    [1124] = {"@Poliwag/Wonderful Picture"},                  -- Poliwag: Good Technique 2
    [130]  = {"@Slowpoke/Wonderful Picture"},                 -- Slowpoke: Good Technique
    [1130] = {"@Slowpoke/Wonderful Picture"},                 -- Slowpoke: Good Technique 2
    [131]  = {"@Slowbro/Wonderful Picture"},                  -- Slowbro: Good Technique
    [1131] = {"@Slowbro/Wonderful Picture"},                  -- Slowbro: Good Technique 2
    [137]  = {"@Shellder/Wonderful Picture"},                 -- Shellder: Good Technique
    [1137] = {"@Shellder/Wonderful Picture"},                 -- Shellder: Good Technique 2
    [138]  = {"@Cloyster/Wonderful Picture"},                 -- Cloyster: Good Technique
    [1138] = {"@Cloyster/Wonderful Picture"},                 -- Cloyster: Good Technique 2
    [156]  = {"@Porygon/Wonderful Picture"},                  -- Porygon: Good Technique
    [1156] = {"@Porygon/Wonderful Picture"},                  -- Porygon: Good Technique 2
    [167]  = {"@Magikarp/River Wonderful Picture"},           -- Magikarp (River): Good Technique
    [1167] = {"@Magikarp/River Wonderful Picture"},           -- Magikarp (River): Good Technique 2
    [171]  = {"@Pikachu/River Wonderful Picture"},            -- Pikachu (River): Good Technique
    [1171] = {"@Pikachu/River Wonderful Picture"},            -- Pikachu (River): Good Technique 2
    [201]  = {"@Bulbasaur/River Same Pkmn"},                  -- Bulbasaur (River): Multiple
    [1201] = {"@Bulbasaur/River Same Pkmn"},                  -- Bulbasaur (River): Multiple 2
    [206]  = {"@Metapod/Same Pkmn"},                          -- Metapod: Multiple
    [1206] = {"@Metapod/Same Pkmn"},                          -- Metapod: Multiple 2
    [220]  = {"@Psyduck/Same Pkmn"},                          -- Psyduck: Multiple
    [1220] = {"@Psyduck/Same Pkmn"},                          -- Psyduck: Multiple 2
    [224]  = {"@Poliwag/Same Pkmn"},                          -- Poliwag: Multiple
    [1224] = {"@Poliwag/Same Pkmn"},                          -- Poliwag: Multiple 2
    [237]  = {"@Shellder/Same Pkmn"},                         -- Shellder: Multiple
    [1237] = {"@Shellder/Same Pkmn"},                         -- Shellder: Multiple 2
    [238]  = {"@Cloyster/Same Pkmn"},                         -- Cloyster: Multiple
    [1238] = {"@Cloyster/Same Pkmn"},                         -- Cloyster: Multiple 2
    [256]  = {"@Porygon/Same Pkmn"},                          -- Porygon: Multiple
    [1256] = {"@Porygon/Same Pkmn"},                          -- Porygon: Multiple 2
    [304]  = {"@Pikachu/Speed Pikachu"},                      -- Speed Pikachu
    [1304] = {"@Pikachu/Speed Pikachu"},                      -- Speed Pikachu 2
    [403]  = {"@River/Pokemon Sign/Cubone Tree"},             -- Cubone Tree
    [1403] = {"@River/Pokemon Sign/Cubone Tree"},             -- Cubone Tree 2
    [503]  = {"@River/Secret Exit/River"},                    -- River: Secret Exit
    [1503] = {"@River/Secret Exit/River"},                    -- River: Secret Exit 2

    -- Cave
    [14]   = {"@Jigglypuff/Picture"},                         -- Jigglypuff
    [1014] = {"@Jigglypuff/Picture"},                         -- Jigglypuff 2
    [25]   = {"@Weepinbell/Picture"},                         -- Weepinbell
    [1025] = {"@Weepinbell/Picture"},                         -- Weepinbell 2
    [26]   = {"@Victreebel/Picture"},                         -- Victreebel
    [1026] = {"@Victreebel/Picture"},                         -- Victreebel 2
    [35]   = {"@Grimer/Picture"},                             -- Grimer
    [1035] = {"@Grimer/Picture"},                             -- Grimer 2
    [36]   = {"@Muk/Picture"},                                -- Muk
    [1036] = {"@Muk/Picture"},                                -- Muk 2
    [41]   = {"@Koffing/Picture"},                            -- Koffing
    [1041] = {"@Koffing/Picture"},                            -- Koffing 2
    [48]   = {"@Jynx/Picture"},                               -- Jynx
    [1048] = {"@Jynx/Picture"},                               -- Jynx 2
    [54]   = {"@Ditto/Picture"},                              -- Ditto
    [1054] = {"@Ditto/Picture"},                              -- Ditto 2
    [58]   = {"@Articuno/Picture"},                           -- Articuno
    [1058] = {"@Articuno/Picture"},                           -- Articuno 2
    [64]   = {"@Bulbasaur/Cave Picture"},                     -- Bulbasaur (Cave)
    [1064] = {"@Bulbasaur/Cave Picture"},                     -- Bulbasaur (Cave) 2
    [68]   = {"@Magikarp/Cave Picture"},                      -- Magikarp (Cave)
    [1068] = {"@Magikarp/Cave Picture"},                      -- Magikarp (Cave) 2
    [72]   = {"@Pikachu/Cave Picture"},                       -- Pikachu (Cave)
    [1072] = {"@Pikachu/Cave Picture"},                       -- Pikachu (Cave) 2
    [73]   = {"@Zubat/Cave Picture"},                         -- Zubat (Cave)
    [1073] = {"@Zubat/Cave Picture"},                         -- Zubat (Cave) 2
    [114]  = {"@Jigglypuff/Wonderful Picture"},               -- Jigglypuff: Good Technique
    [1114] = {"@Jigglypuff/Wonderful Picture"},               -- Jigglypuff: Good Technique 2
    [125]  = {"@Weepinbell/Wonderful Picture"},               -- Weepinbell: Good Technique
    [1125] = {"@Weepinbell/Wonderful Picture"},               -- Weepinbell: Good Technique 2
    [126]  = {"@Victreebel/Wonderful Picture"},               -- Victreebel: Good Technique
    [1126] = {"@Victreebel/Wonderful Picture"},               -- Victreebel: Good Technique 2
    [135]  = {"@Grimer/Wonderful Picture"},                   -- Grimer: Good Technique
    [1135] = {"@Grimer/Wonderful Picture"},                   -- Grimer: Good Technique 2
    [136]  = {"@Muk/Wonderful Picture"},                      -- Muk: Good Technique
    [1136] = {"@Muk/Wonderful Picture"},                      -- Muk: Good Technique 2
    [141]  = {"@Koffing/Wonderful Picture"},                  -- Koffing: Good Technique
    [1141] = {"@Koffing/Wonderful Picture"},                  -- Koffing: Good Technique 2
    [148]  = {"@Jynx/Wonderful Picture"},                     -- Jynx: Good Technique
    [1148] = {"@Jynx/Wonderful Picture"},                     -- Jynx: Good Technique 2
    [154]  = {"@Ditto/Wonderful Picture"},                    -- Ditto: Good Technique
    [1154] = {"@Ditto/Wonderful Picture"},                    -- Ditto: Good Technique 2
    [158]  = {"@Articuno/Wonderful Picture"},                 -- Articuno: Good Technique
    [1158] = {"@Articuno/Wonderful Picture"},                 -- Articuno: Good Technique 2
    [164]  = {"@Bulbasaur/Cave Wonderful Picture"},           -- Bulbasaur (Cave): Good Technique
    [1164] = {"@Bulbasaur/Cave Wonderful Picture"},           -- Bulbasaur (Cave): Good Technique 2
    [168]  = {"@Magikarp/Cave Wonderful Picture"},            -- Magikarp (Cave): Good Technique
    [1168] = {"@Magikarp/Cave Wonderful Picture"},            -- Magikarp (Cave): Good Technique 2
    [172]  = {"@Pikachu/Cave Wonderful Picture"},             -- Pikachu (Cave): Good Technique
    [1172] = {"@Pikachu/Cave Wonderful Picture"},             -- Pikachu (Cave): Good Technique 2
    [173]  = {"@Zubat/Cave Wonderful Picture"},               -- Zubat (Cave): Good Technique
    [1173] = {"@Zubat/Cave Wonderful Picture"},               -- Zubat (Cave): Good Technique 2
    [214]  = {"@Jigglypuff/Same Pkmn"},                       -- Jigglypuff: Multiple
    [1214] = {"@Jigglypuff/Same Pkmn"},                       -- Jigglypuff: Multiple 2
    [248]  = {"@Jynx/Same Pkmn"},                             -- Jynx: Multiple
    [1248] = {"@Jynx/Same Pkmn"},                             -- Jynx: Multiple 2
    [254]  = {"@Ditto/Same Pkmn"},                            -- Ditto: Multiple
    [1254] = {"@Ditto/Same Pkmn"},                            -- Ditto: Multiple 2
    [264]  = {"@Bulbasaur/Cave Same Pkmn"},                   -- Bulbasaur (Cave): Multiple
    [1264] = {"@Bulbasaur/Cave Same Pkmn"},                   -- Bulbasaur (Cave): Multiple 2
    [273]  = {"@Zubat/Same Pkmn"},                            -- Zubat (Cave): Multiple
    [1273] = {"@Zubat/Same Pkmn"},                            -- Zubat (Cave): Multiple 2
    [303]  = {"@Pikachu/Balloon Pikachu"},                    -- Balloon Pikachu
    [1303] = {"@Pikachu/Balloon Pikachu"},                    -- Balloon Pikachu 2
    [306]  = {"@Pikachu/Flying Pikachu"},                     -- Flying Pikachu
    [1306] = {"@Pikachu/Flying Pikachu"},                     -- Flying Pikachu 2
    [308]  = {"@Jigglypuff/Jigglypuff on Stage"},             -- Jigglypuff on Stage
    [1308] = {"@Jigglypuff/Jigglypuff on Stage"},             -- Jigglypuff on Stage 2
    [312]  = {"@Jigglypuff/Jigglypuff Trio on Stage"},        -- Jigglypuff Trio on Stage
    [1312] = {"@Jigglypuff/Jigglypuff Trio on Stage"},        -- Jigglypuff Trio on Stage 2
    [404]  = {"@Cave/Pokemon Sign/Constellation of Mewtwo"},  -- The Mewtwo Constellation
    [1404] = {"@Cave/Pokemon Sign/Constellation of Mewtwo"},  -- The Mewtwo Constellation 2

    -- Valley
    [5]    = {"@Squirtle/Picture"},                           -- Squirtle
    [1005] = {"@Squirtle/Picture"},                           -- Squirtle 2
    [11]   = {"@Sandshrew/Picture"},                          -- Sandshrew
    [1011] = {"@Sandshrew/Picture"},                          -- Sandshrew 2
    [12]   = {"@Sandslash/Picture"},                          -- Sandslash
    [1012] = {"@Sandslash/Picture"},                          -- Sandslash 2
    [21]   = {"@Mankey/Picture"},                             -- Mankey
    [1021] = {"@Mankey/Picture"},                             -- Mankey 2
    [27]   = {"@Geodude/Picture"},                            -- Geodude
    [1027] = {"@Geodude/Picture"},                            -- Geodude 2
    [28]   = {"@Graveler/Picture"},                           -- Graveler
    [1028] = {"@Graveler/Picture"},                           -- Graveler 2
    [44]   = {"@Goldeen/Picture"},                            -- Goldeen
    [1044] = {"@Goldeen/Picture"},                            -- Goldeen 2
    [45]   = {"@Staryu/Picture"},                             -- Staryu
    [1045] = {"@Staryu/Picture"},                             -- Staryu 2
    [46]   = {"@Starmie/Picture"},                            -- Starmie
    [1046] = {"@Starmie/Picture"},                            -- Starmie 2
    [52]   = {"@Gyarados/Picture"},                           -- Gyarados
    [1052] = {"@Gyarados/Picture"},                           -- Gyarados 2
    [61]   = {"@Dratini/Picture"},                            -- Dratini
    [1061] = {"@Dratini/Picture"},                            -- Dratini 2
    [62]   = {"@Dragonite/Picture"},                          -- Dragonite
    [1062] = {"@Dragonite/Picture"},                          -- Dragonite 2
    [69]   = {"@Magikarp/Valley Picture"},                    -- Magikarp (Valley)
    [1069] = {"@Magikarp/Valley Picture"},                    -- Magikarp (Valley) 2
    [105]  = {"@Squirtle/Wonderful Picture"},                 -- Squirtle: Good Technique
    [1105] = {"@Squirtle/Wonderful Picture"},                 -- Squirtle: Good Technique 2
    [111]  = {"@Sandshrew/Wonderful Picture"},                -- Sandshrew: Good Technique
    [1111] = {"@Sandshrew/Wonderful Picture"},                -- Sandshrew: Good Technique 2
    [112]  = {"@Sandslash/Wonderful Picture"},                -- Sandslash: Good Technique
    [1112] = {"@Sandslash/Wonderful Picture"},                -- Sandslash: Good Technique 2
    [121]  = {"@Mankey/Wonderful Picture"},                   -- Mankey: Good Technique
    [1121] = {"@Mankey/Wonderful Picture"},                   -- Mankey: Good Technique 2
    [127]  = {"@Geodude/Wonderful Picture"},                  -- Geodude: Good Technique
    [1127] = {"@Geodude/Wonderful Picture"},                  -- Geodude: Good Technique 2
    [128]  = {"@Graveler/Wonderful Picture"},                 -- Graveler: Good Technique
    [1128] = {"@Graveler/Wonderful Picture"},                 -- Graveler: Good Technique 2
    [144]  = {"@Goldeen/Wonderful Picture"},                  -- Goldeen: Good Technique
    [1144] = {"@Goldeen/Wonderful Picture"},                  -- Goldeen: Good Technique 2
    [145]  = {"@Staryu/Wonderful Picture"},                   -- Staryu: Good Technique
    [1145] = {"@Staryu/Wonderful Picture"},                   -- Staryu: Good Technique 2
    [146]  = {"@Starmie/Wonderful Picture"},                  -- Starmie: Good Technique
    [1146] = {"@Starmie/Wonderful Picture"},                  -- Starmie: Good Technique 2
    [152]  = {"@Gyarados/Wonderful Picture"},                 -- Gyarados: Good Technique
    [1152] = {"@Gyarados/Wonderful Picture"},                 -- Gyarados: Good Technique 2
    [161]  = {"@Dratini/Wonderful Picture"},                  -- Dratini: Good Technique
    [1161] = {"@Dratini/Wonderful Picture"},                  -- Dratini: Good Technique 2
    [162]  = {"@Dragonite/Wonderful Picture"},                -- Dragonite: Good Technique
    [1162] = {"@Dragonite/Wonderful Picture"},                -- Dragonite: Good Technique 2
    [169]  = {"@Magikarp/Valley Wonderful Picture"},          -- Magikarp (Valley): Good Technique
    [1169] = {"@Magikarp/Valley Wonderful Picture"},          -- Magikarp (Valley): Good Technique 2
    [205]  = {"@Squirtle/Same Pkmn"},                         -- Squirtle: Multiple
    [1205] = {"@Squirtle/Same Pkmn"},                         -- Squirtle: Multiple 2
    [211]  = {"@Sandshrew/Same Pkmn"},                        -- Sandshrew: Multiple
    [1211] = {"@Sandshrew/Same Pkmn"},                        -- Sandshrew: Multiple 2
    [227]  = {"@Geodude/Same Pkmn"},                          -- Geodude: Multiple
    [1227] = {"@Geodude/Same Pkmn"},                          -- Geodude: Multiple 2
    [228]  = {"@Graveler/Same Pkmn"},                         -- Graveler: Multiple
    [1228] = {"@Graveler/Same Pkmn"},                         -- Graveler: Multiple 2
    [245]  = {"@Staryu/Same Pkmn"},                           -- Staryu: Multiple
    [1245] = {"@Staryu/Same Pkmn"},                           -- Staryu: Multiple 2
    [246]  = {"@Starmie/Same Pkmn"},                          -- Starmie: Multiple
    [1246] = {"@Starmie/Same Pkmn"},                          -- Starmie: Multiple 2
    [261]  = {"@Dratini/Same Pkmn"},                          -- Dratini: Multiple
    [1261] = {"@Dratini/Same Pkmn"},                          -- Dratini: Multiple 2
    [269]  = {"@Magikarp/Same Pkmn"},                         -- Magikarp (Valley): Multiple
    [1269] = {"@Magikarp/Same Pkmn"},                         -- Magikarp (Valley): Multiple 2
    [309]  = {"@Graveler/Graveler's Group Dance"},            -- Graveler's Group Dance
    [1309] = {"@Graveler/Graveler's Group Dance"},            -- Graveler's Group Dance 2
    [405]  = {"@Valley/Pokemon Sign/Mt Dugtrio"},             -- Dugtrio Mountain
    [1405] = {"@Valley/Pokemon Sign/Mt Dugtrio"},             -- Dugtrio Mountain 2
    [505]  = {"@Valley/Mankey & Exit/Secret Exit: Valley"},   -- Valley: Secret Exit
    [1505] = {"@Valley/Mankey & Exit/Secret Exit: Valley"},   -- Valley: Secret Exit 2

    -- Rainbow Cloud
    [63]   = {"@Mew/Picture (Game Completion)"},              -- Mew
    [1063] = {"@Mew/Picture (Game Completion)"},              -- Mew 2

    -- Oak's Lab (apworld 0.6.0)
    [601]  = {"@Oak's Lab & Rainbow Cloud/Report Scores/24,000 PKMN Report Score"}, -- 24,000 PKMN Report Score
    [1601] = {"@Oak's Lab & Rainbow Cloud/Report Scores/24,000 PKMN Report Score"}, -- 24,000 PKMN Report Score 2
    [602]  = {"@Oak's Lab & Rainbow Cloud/Report Scores/72,500 PKMN Report Score"}, -- 72,500 PKMN Report Score
    [1602] = {"@Oak's Lab & Rainbow Cloud/Report Scores/72,500 PKMN Report Score"}, -- 72,500 PKMN Report Score 2
    [603]  = {"@Oak's Lab & Rainbow Cloud/Report Scores/130,000 PKMN Report Score"}, -- 130,000 PKMN Report Score
    [1603] = {"@Oak's Lab & Rainbow Cloud/Report Scores/130,000 PKMN Report Score"}, -- 130,000 PKMN Report Score 2
    [604]  = {"@Oak's Lab & Rainbow Cloud/Pokemon Photographed/6 Pokemon Photographed"}, -- 6 Pokemon Photographed
    [1604] = {"@Oak's Lab & Rainbow Cloud/Pokemon Photographed/6 Pokemon Photographed"}, -- 6 Pokemon Photographed 2
    [605]  = {"@Oak's Lab & Rainbow Cloud/Pokemon Photographed/22 Pokemon Photographed"}, -- 22 Pokemon Photographed
    [1605] = {"@Oak's Lab & Rainbow Cloud/Pokemon Photographed/22 Pokemon Photographed"}, -- 22 Pokemon Photographed 2
    [606]  = {"@Oak's Lab & Rainbow Cloud/Pokemon Photographed/40 Pokemon Photographed"}, -- 40 Pokemon Photographed
    [1606] = {"@Oak's Lab & Rainbow Cloud/Pokemon Photographed/40 Pokemon Photographed"}, -- 40 Pokemon Photographed 2
}
