-- AP location id -> PopTracker section
-- Target: Pokemon Snap apworld world_version 0.4.0
--
-- ID scheme (locations.py):
--   base photo       = species id          (1-73)
--   ": Good Technique" = species id + 100  (101-173)
--   ": Multiple"     = species id + 200    (201-273)
--   special poses    = 301-312
--   Pokemon signs    = 400-405
--   secret exits     = 501 / 503 / 505
LOCATION_MAPPING = {

    -- Beach
    [7]    = {"@Butterfree/Picture"},                         -- Butterfree
    [9]    = {"@Pidgey/Picture"},                             -- Pidgey
    [10]   = {"@Pikachu/Beach Picture"},                      -- Pikachu (Beach)
    [19]   = {"@Meowth/Picture"},                             -- Meowth
    [34]   = {"@Doduo/Picture"},                              -- Doduo
    [42]   = {"@Chansey/Picture"},                            -- Chansey
    [43]   = {"@Kangaskhan/Picture"},                         -- Kangaskhan
    [47]   = {"@Scyther/Picture"},                            -- Scyther
    [51]   = {"@Magikarp/Beach Picture"},                     -- Magikarp (Beach)
    [53]   = {"@Lapras/Picture"},                             -- Lapras
    [55]   = {"@Eevee/Picture"},                              -- Eevee
    [57]   = {"@Snorlax/Picture"},                            -- Snorlax
    [107]  = {"@Butterfree/Wonderful Picture"},               -- Butterfree: Good Technique
    [109]  = {"@Pidgey/Wonderful Picture"},                   -- Pidgey: Good Technique
    [110]  = {"@Pikachu/Beach Wonderful Picture"},            -- Pikachu (Beach): Good Technique
    [119]  = {"@Meowth/Wonderful Picture"},                   -- Meowth: Good Technique
    [134]  = {"@Doduo/Wonderful Picture"},                    -- Doduo: Good Technique
    [142]  = {"@Chansey/Wonderful Picture"},                  -- Chansey: Good Technique
    [143]  = {"@Kangaskhan/Wonderful Picture"},               -- Kangaskhan: Good Technique
    [147]  = {"@Scyther/Wonderful Picture"},                  -- Scyther: Good Technique
    [151]  = {"@Magikarp/Beach Wonderful Picture"},           -- Magikarp (Beach): Good Technique
    [153]  = {"@Lapras/Wonderful Picture"},                   -- Lapras: Good Technique
    [155]  = {"@Eevee/Wonderful Picture"},                    -- Eevee: Good Technique
    [157]  = {"@Snorlax/Wonderful Picture"},                  -- Snorlax: Good Technique
    [207]  = {"@Butterfree/Same Pkmn"},                       -- Butterfree: Multiple
    [209]  = {"@Pidgey/Same Pkmn"},                           -- Pidgey: Multiple
    [210]  = {"@Pikachu/Same Pkmn"},                          -- Pikachu (Beach): Multiple
    [253]  = {"@Lapras/Same Pkmn"},                           -- Lapras: Multiple
    [301]  = {"@Pikachu/Surfing Pikachu"},                    -- Surfing Pikachu
    [305]  = {"@Pikachu/Pikachu on a Stump"},                 -- Pikachu on a Stump
    [307]  = {"@Pidgey/Gust-Using Pidgey"},                   -- Gust-Using Pidgey
    [400]  = {"@Beach/Pokemon Sign/Kingler Rock"},            -- Kingler Rock

    -- Tunnel
    [8]    = {"@Kakuna/Picture"},                             -- Kakuna
    [15]   = {"@Zubat/Tunnel Picture"},                       -- Zubat (Tunnel)
    [17]   = {"@Diglett/Picture"},                            -- Diglett
    [18]   = {"@Dugtrio/Picture"},                            -- Dugtrio
    [32]   = {"@Magnemite/Picture"},                          -- Magnemite
    [33]   = {"@Magneton/Picture"},                           -- Magneton
    [39]   = {"@Haunter/Picture"},                            -- Haunter
    [40]   = {"@Electrode/Picture"},                          -- Electrode
    [49]   = {"@Electabuzz/Picture"},                         -- Electabuzz
    [59]   = {"@Zapdos/Picture"},                             -- Zapdos
    [65]   = {"@Magikarp/Tunnel Picture"},                    -- Magikarp (Tunnel)
    [70]   = {"@Pikachu/Tunnel Picture"},                     -- Pikachu (Tunnel)
    [108]  = {"@Kakuna/Wonderful Picture"},                   -- Kakuna: Good Technique
    [115]  = {"@Zubat/Tunnel Wonderful Picture"},             -- Zubat (Tunnel): Good Technique
    [117]  = {"@Diglett/Wonderful Picture"},                  -- Diglett: Good Technique
    [118]  = {"@Dugtrio/Wonderful Picture"},                  -- Dugtrio: Good Technique
    [132]  = {"@Magnemite/Wonderful Picture"},                -- Magnemite: Good Technique
    [133]  = {"@Magneton/Wonderful Picture"},                 -- Magneton: Good Technique
    [139]  = {"@Haunter/Wonderful Picture"},                  -- Haunter: Good Technique
    [140]  = {"@Electrode/Wonderful Picture"},                -- Electrode: Good Technique
    [149]  = {"@Electabuzz/Wonderful Picture"},               -- Electabuzz: Good Technique
    [159]  = {"@Zapdos/Wonderful Picture"},                   -- Zapdos: Good Technique
    [165]  = {"@Magikarp/Tunnel Wonderful Picture"},          -- Magikarp (Tunnel): Good Technique
    [170]  = {"@Pikachu/Tunnel Wonderful Picture"},           -- Pikachu (Tunnel): Good Technique
    [208]  = {"@Kakuna/Same Pkmn"},                           -- Kakuna: Multiple
    [218]  = {"@Dugtrio/Same Pkmn"},                          -- Dugtrio: Multiple
    [232]  = {"@Magnemite/Same Pkmn"},                        -- Magnemite: Multiple
    [240]  = {"@Electrode/Same Pkmn"},                        -- Electrode: Multiple
    [249]  = {"@Electabuzz/Same Pkmn"},                       -- Electabuzz: Multiple
    [302]  = {"@Pikachu/Pikachu on a Ball"},                  -- Pikachu on a Ball
    [401]  = {"@Tunnel/Pokemon Sign/Pinsir Shadow"},          -- Pinsir's Shadow
    [501]  = {"@Tunnel/Secret Exit/Tunnel"},                  -- Tunnel: Secret Exit

    -- Volcano
    [2]    = {"@Charmander/Picture"},                         -- Charmander
    [3]    = {"@Charmeleon/Picture"},                         -- Charmeleon
    [4]    = {"@Charizard/Picture"},                          -- Charizard
    [13]   = {"@Vulpix/Picture"},                             -- Vulpix
    [22]   = {"@Growlithe/Picture"},                          -- Growlithe
    [23]   = {"@Arcanine/Picture"},                           -- Arcanine
    [29]   = {"@Rapidash/Picture"},                           -- Rapidash
    [50]   = {"@Magmar/Picture"},                             -- Magmar
    [60]   = {"@Moltres/Picture"},                            -- Moltres
    [66]   = {"@Magikarp/Volcano Picture"},                   -- Magikarp (Volcano)
    [102]  = {"@Charmander/Wonderful Picture"},               -- Charmander: Good Technique
    [103]  = {"@Charmeleon/Wonderful Picture"},               -- Charmeleon: Good Technique
    [104]  = {"@Charizard/Wonderful Picture"},                -- Charizard: Good Technique
    [113]  = {"@Vulpix/Wonderful Picture"},                   -- Vulpix: Good Technique
    [122]  = {"@Growlithe/Wonderful Picture"},                -- Growlithe: Good Technique
    [123]  = {"@Arcanine/Wonderful Picture"},                 -- Arcanine: Good Technique
    [129]  = {"@Rapidash/Wonderful Picture"},                 -- Rapidash: Good Technique
    [150]  = {"@Magmar/Wonderful Picture"},                   -- Magmar: Good Technique
    [160]  = {"@Moltres/Wonderful Picture"},                  -- Moltres: Good Technique
    [166]  = {"@Magikarp/Volcano Wonderful Picture"},         -- Magikarp (Volcano): Good Technique
    [202]  = {"@Charmander/Same Pkmn"},                       -- Charmander: Multiple
    [213]  = {"@Vulpix/Same Pkmn"},                           -- Vulpix: Multiple
    [222]  = {"@Growlithe/Same Pkmn"},                        -- Growlithe: Multiple
    [223]  = {"@Arcanine/Same Pkmn"},                         -- Arcanine: Multiple
    [229]  = {"@Rapidash/Same Pkmn"},                         -- Rapidash: Multiple
    [250]  = {"@Magmar/Same Pkmn"},                           -- Magmar: Multiple
    [311]  = {"@Magmar/Fighting Magmar"},                     -- Fighting Magmar
    [402]  = {"@Volcano/Pokemon Sign/Koffing Smoke"},         -- Koffing Smoke

    -- River
    [1]    = {"@Bulbasaur/River Picture"},                    -- Bulbasaur (River)
    [6]    = {"@Metapod/Picture"},                            -- Metapod
    [16]   = {"@Vileplume/Picture"},                          -- Vileplume
    [20]   = {"@Psyduck/Picture"},                            -- Psyduck
    [24]   = {"@Poliwag/Picture"},                            -- Poliwag
    [30]   = {"@Slowpoke/Picture"},                           -- Slowpoke
    [31]   = {"@Slowbro/Picture"},                            -- Slowbro
    [37]   = {"@Shellder/Picture"},                           -- Shellder
    [38]   = {"@Cloyster/Picture"},                           -- Cloyster
    [56]   = {"@Porygon/Picture"},                            -- Porygon
    [67]   = {"@Magikarp/River Picture"},                     -- Magikarp (River)
    [71]   = {"@Pikachu/River Picture"},                      -- Pikachu (River)
    [101]  = {"@Bulbasaur/River Wonderful Picture"},          -- Bulbasaur (River): Good Technique
    [106]  = {"@Metapod/Wonderful Picture"},                  -- Metapod: Good Technique
    [116]  = {"@Vileplume/Wonderful Picture"},                -- Vileplume: Good Technique
    [120]  = {"@Psyduck/Wonderful Picture"},                  -- Psyduck: Good Technique
    [124]  = {"@Poliwag/Wonderful Picture"},                  -- Poliwag: Good Technique
    [130]  = {"@Slowpoke/Wonderful Picture"},                 -- Slowpoke: Good Technique
    [131]  = {"@Slowbro/Wonderful Picture"},                  -- Slowbro: Good Technique
    [137]  = {"@Shellder/Wonderful Picture"},                 -- Shellder: Good Technique
    [138]  = {"@Cloyster/Wonderful Picture"},                 -- Cloyster: Good Technique
    [156]  = {"@Porygon/Wonderful Picture"},                  -- Porygon: Good Technique
    [167]  = {"@Magikarp/River Wonderful Picture"},           -- Magikarp (River): Good Technique
    [171]  = {"@Pikachu/River Wonderful Picture"},            -- Pikachu (River): Good Technique
    [201]  = {"@Bulbasaur/River Same Pkmn"},                  -- Bulbasaur (River): Multiple
    [206]  = {"@Metapod/Same Pkmn"},                          -- Metapod: Multiple
    [220]  = {"@Psyduck/Same Pkmn"},                          -- Psyduck: Multiple
    [224]  = {"@Poliwag/Same Pkmn"},                          -- Poliwag: Multiple
    [237]  = {"@Shellder/Same Pkmn"},                         -- Shellder: Multiple
    [238]  = {"@Cloyster/Same Pkmn"},                         -- Cloyster: Multiple
    [256]  = {"@Porygon/Same Pkmn"},                          -- Porygon: Multiple
    [304]  = {"@Pikachu/Speed Pikachu"},                      -- Speed Pikachu
    [403]  = {"@River/Pokemon Sign/Cubone Tree"},             -- Cubone Tree
    [503]  = {"@River/Secret Exit/River"},                    -- River: Secret Exit

    -- Cave
    [14]   = {"@Jigglypuff/Picture"},                         -- Jigglypuff
    [25]   = {"@Weepinbell/Picture"},                         -- Weepinbell
    [26]   = {"@Victreebel/Picture"},                         -- Victreebel
    [35]   = {"@Grimer/Picture"},                             -- Grimer
    [36]   = {"@Muk/Picture"},                                -- Muk
    [41]   = {"@Koffing/Picture"},                            -- Koffing
    [48]   = {"@Jynx/Picture"},                               -- Jynx
    [54]   = {"@Ditto/Picture"},                              -- Ditto
    [58]   = {"@Articuno/Picture"},                           -- Articuno
    [64]   = {"@Bulbasaur/Cave Picture"},                     -- Bulbasaur (Cave)
    [68]   = {"@Magikarp/Cave Picture"},                      -- Magikarp (Cave)
    [72]   = {"@Pikachu/Cave Picture"},                       -- Pikachu (Cave)
    [73]   = {"@Zubat/Cave Picture"},                         -- Zubat (Cave)
    [114]  = {"@Jigglypuff/Wonderful Picture"},               -- Jigglypuff: Good Technique
    [125]  = {"@Weepinbell/Wonderful Picture"},               -- Weepinbell: Good Technique
    [126]  = {"@Victreebel/Wonderful Picture"},               -- Victreebel: Good Technique
    [135]  = {"@Grimer/Wonderful Picture"},                   -- Grimer: Good Technique
    [136]  = {"@Muk/Wonderful Picture"},                      -- Muk: Good Technique
    [141]  = {"@Koffing/Wonderful Picture"},                  -- Koffing: Good Technique
    [148]  = {"@Jynx/Wonderful Picture"},                     -- Jynx: Good Technique
    [154]  = {"@Ditto/Wonderful Picture"},                    -- Ditto: Good Technique
    [158]  = {"@Articuno/Wonderful Picture"},                 -- Articuno: Good Technique
    [164]  = {"@Bulbasaur/Cave Wonderful Picture"},           -- Bulbasaur (Cave): Good Technique
    [168]  = {"@Magikarp/Cave Wonderful Picture"},            -- Magikarp (Cave): Good Technique
    [172]  = {"@Pikachu/Cave Wonderful Picture"},             -- Pikachu (Cave): Good Technique
    [173]  = {"@Zubat/Cave Wonderful Picture"},               -- Zubat (Cave): Good Technique
    [214]  = {"@Jigglypuff/Same Pkmn"},                       -- Jigglypuff: Multiple
    [248]  = {"@Jynx/Same Pkmn"},                             -- Jynx: Multiple
    [254]  = {"@Ditto/Same Pkmn"},                            -- Ditto: Multiple
    [264]  = {"@Bulbasaur/Cave Same Pkmn"},                   -- Bulbasaur (Cave): Multiple
    [273]  = {"@Zubat/Same Pkmn"},                            -- Zubat (Cave): Multiple
    [303]  = {"@Pikachu/Balloon Pikachu"},                    -- Balloon Pikachu
    [306]  = {"@Pikachu/Flying Pikachu"},                     -- Flying Pikachu
    [308]  = {"@Jigglypuff/Jigglypuff on Stage"},             -- Jigglypuff on Stage
    [312]  = {"@Jigglypuff/Jigglypuff Trio on Stage"},        -- Jigglypuff Trio on Stage
    [404]  = {"@Cave/Pokemon Sign/Constellation of Mewtwo"},  -- The Mewtwo Constellation

    -- Valley
    [5]    = {"@Squirtle/Picture"},                           -- Squirtle
    [11]   = {"@Sandshrew/Picture"},                          -- Sandshrew
    [12]   = {"@Sandslash/Picture"},                          -- Sandslash
    [21]   = {"@Mankey/Picture"},                             -- Mankey
    [27]   = {"@Geodude/Picture"},                            -- Geodude
    [28]   = {"@Graveler/Picture"},                           -- Graveler
    [44]   = {"@Goldeen/Picture"},                            -- Goldeen
    [45]   = {"@Staryu/Picture"},                             -- Staryu
    [46]   = {"@Starmie/Picture"},                            -- Starmie
    [52]   = {"@Gyarados/Picture"},                           -- Gyarados
    [61]   = {"@Dratini/Picture"},                            -- Dratini
    [62]   = {"@Dragonite/Picture"},                          -- Dragonite
    [69]   = {"@Magikarp/Valley Picture"},                    -- Magikarp (Valley)
    [105]  = {"@Squirtle/Wonderful Picture"},                 -- Squirtle: Good Technique
    [111]  = {"@Sandshrew/Wonderful Picture"},                -- Sandshrew: Good Technique
    [112]  = {"@Sandslash/Wonderful Picture"},                -- Sandslash: Good Technique
    [121]  = {"@Mankey/Wonderful Picture"},                   -- Mankey: Good Technique
    [127]  = {"@Geodude/Wonderful Picture"},                  -- Geodude: Good Technique
    [128]  = {"@Graveler/Wonderful Picture"},                 -- Graveler: Good Technique
    [144]  = {"@Goldeen/Wonderful Picture"},                  -- Goldeen: Good Technique
    [145]  = {"@Staryu/Wonderful Picture"},                   -- Staryu: Good Technique
    [146]  = {"@Starmie/Wonderful Picture"},                  -- Starmie: Good Technique
    [152]  = {"@Gyarados/Wonderful Picture"},                 -- Gyarados: Good Technique
    [161]  = {"@Dratini/Wonderful Picture"},                  -- Dratini: Good Technique
    [162]  = {"@Dragonite/Wonderful Picture"},                -- Dragonite: Good Technique
    [169]  = {"@Magikarp/Valley Wonderful Picture"},          -- Magikarp (Valley): Good Technique
    [205]  = {"@Squirtle/Same Pkmn"},                         -- Squirtle: Multiple
    [211]  = {"@Sandshrew/Same Pkmn"},                        -- Sandshrew: Multiple
    [227]  = {"@Geodude/Same Pkmn"},                          -- Geodude: Multiple
    [228]  = {"@Graveler/Same Pkmn"},                         -- Graveler: Multiple
    [245]  = {"@Staryu/Same Pkmn"},                           -- Staryu: Multiple
    [246]  = {"@Starmie/Same Pkmn"},                          -- Starmie: Multiple
    [261]  = {"@Dratini/Same Pkmn"},                          -- Dratini: Multiple
    [269]  = {"@Magikarp/Same Pkmn"},                         -- Magikarp (Valley): Multiple
    [309]  = {"@Graveler/Graveler's Group Dance"},            -- Graveler's Group Dance
    [405]  = {"@Valley/Pokemon Sign/Mt Dugtrio"},             -- Dugtrio Mountain
    [505]  = {"@Valley/Mankey & Exit/Secret Exit: Valley"},   -- Valley: Secret Exit

    -- Rainbow Cloud
    [63]   = {"@Mew/Picture (Game Completion)"},              -- Mew
}
