-- Generated by tools/make_oak_mapping.py -- do not edit by hand.
-- Built from apworld world_version 0.7.0.
--
-- OAK_PHOTO_IDS  every base photo location, one per entry, which is
--                exactly the list AtLeast() counts for the photo checks.
-- OAK_SPECIES    those ids grouped by species; the report score takes the
--                best course per species instead of adding them together.
-- OAK_NO_BONUS   wonderful/multiple ids the score estimate always ignores
--                because they are rng or hard photos.

OAK_PHOTO_IDS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73}

OAK_SPECIES = {
    {1, 64},   -- Bulbasaur
    {2},
    {3},
    {4},
    {5},
    {6},
    {7},
    {8},
    {9},
    {10, 70, 71, 72},   -- Pikachu
    {11},
    {12},
    {13},
    {14},
    {15, 73},   -- Zubat
    {16},
    {17},
    {18},
    {19},
    {20},
    {21},
    {22},
    {23},
    {24},
    {25},
    {26},
    {27},
    {28},
    {29},
    {30},
    {31},
    {32},
    {33},
    {34},
    {35},
    {36},
    {37},
    {38},
    {39},
    {40},
    {41},
    {42},
    {43},
    {44},
    {45},
    {46},
    {47},
    {48},
    {49},
    {50},
    {51, 65, 66, 67, 68, 69},   -- Magikarp
    {52},
    {53},
    {54},
    {55},
    {56},
    {57},
    {58},
    {59},
    {60},
    {61},
    {62},
    {63},
}

OAK_NO_BONUS = {
    [144] = true,   -- Goldeen: Good Technique
    [168] = true,   -- Magikarp (Cave): Good Technique
    [171] = true,   -- Pikachu (River): Good Technique
    [220] = true,   -- Psyduck: Multiple
    [223] = true,   -- Arcanine: Multiple
    [238] = true,   -- Cloyster: Multiple
    [245] = true,   -- Staryu: Multiple
    [246] = true,   -- Starmie: Multiple
    [261] = true,   -- Dratini: Multiple
    [269] = true,   -- Magikarp (Valley): Multiple
    [273] = true,   -- Zubat (Cave): Multiple
}
