-- Access rules for Oak's six rewards.
--
-- These are the only checks in the game whose requirement is not "do you hold
-- item X" but "can you reach enough of the rest of the game", so they cannot
-- be written as ordinary access rules:
--
--   N Pokemon Photographed   AtLeast(N, <every base photo location>)
--   X PKMN Report Score      a per-species score estimate, summed
--
-- Both are answered by asking each photo section whether it is currently in
-- logic, which is what CanReachLocation does on the Archipelago side.
--
-- The score mirrors ReportScoreAchievable in the apworld exactly: 200 for a
-- species you can photograph, (200 + 900) * 2 if you could also get the Good
-- Technique bonus, plus 150 for Multiple. A species reachable in more than one
-- course counts once, at its best course, rather than once per course.
--
-- OAK_PHOTO_IDS / OAK_SPECIES / OAK_NO_BONUS come from oak_mapping.lua, which
-- is generated by tools/make_oak_mapping.py.

local function section_path(id)
    local entry = LOCATION_MAPPING and LOCATION_MAPPING[id]
    return entry and entry[1]
end

-- In logic now, or already checked. Deliberately not SequenceBreak: the
-- apworld's CanReachLocation uses normal logic, and counting glitched routes
-- here would light these up earlier than Archipelago considers them possible.
local function reachable(id)
    local path = section_path(id)
    if not path then return false end
    local obj = Tracker:FindObjectForCode(path)
    if not obj then return false end
    local level = obj.AccessibilityLevel
    if level == nil then return false end
    return level >= AccessibilityLevel.Normal
end

function oak_photo_count()
    local n = 0
    for _, id in ipairs(OAK_PHOTO_IDS or {}) do
        if reachable(id) then n = n + 1 end
    end
    return n
end

function oak_report_score()
    local total = 0
    for _, ids in ipairs(OAK_SPECIES or {}) do
        local best = 0
        for _, id in ipairs(ids) do
            if reachable(id) then
                local score = 200
                local wonderful, multiple = id + 100, id + 200
                if not (OAK_NO_BONUS or {})[wonderful] and reachable(wonderful) then
                    score = (score + 900) * 2
                end
                if not (OAK_NO_BONUS or {})[multiple] and reachable(multiple) then
                    score = score + 150
                end
                if score > best then best = score end
            end
        end
        total = total + best
    end
    return total
end

function oak_photo_6()  return oak_photo_count() >= 6  and 1 or 0 end
function oak_photo_22() return oak_photo_count() >= 22 and 1 or 0 end
function oak_photo_40() return oak_photo_count() >= 40 and 1 or 0 end

function oak_score_24000()  return oak_report_score() >= 24000  and 1 or 0 end
function oak_score_72500()  return oak_report_score() >= 72500  and 1 or 0 end
function oak_score_130000() return oak_report_score() >= 130000 and 1 or 0 end
