"""Generate scripts/autotracking/oak_mapping.lua from an apworld.

The six Oak rewards are not "do you hold item X" rules, so they cannot be
written as access rules by hand:

  N Pokemon Photographed   AtLeast(N, <every base photo location>)
  X PKMN Report Score      a heuristic that scores every species it can reach

Both need to know which base photos exist and which belong to the same
species, because the score takes the best course per species rather than
adding them up. The apworld also drops rng/hard photos from the score estimate
regardless of whether the seed includes them. All of that is emitted here so
oak.lua can stay short.

    python tools/make_oak_mapping.py "path/to/pokemon_snap.apworld"
"""
import sys, importlib, importlib.util, collections
from pathlib import Path

PACK = Path(__file__).resolve().parent.parent
OUT = PACK / "scripts" / "autotracking" / "oak_mapping.lua"


def main(apworld):
    spec = importlib.util.spec_from_file_location(
        "_check", PACK / "tools" / "check_apworld.py")
    check = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(check)
    version, locs, items, root = check.load_apworld(apworld)
    L = importlib.import_module("pokemon_snap.locations")

    cat = {}
    for table in L.location_tables.values():
        for d in table:
            cat[d.id] = (d.category.name, d.name)

    base = sorted(i for i, (c, _) in cat.items() if c == "NORMAL_PHOTO" and i < 1000)

    # "Pikachu (River)" and "Pikachu" are the same species for scoring
    def species(name):
        return name.split(" (")[0].strip()

    groups = collections.OrderedDict()
    for i in base:
        groups.setdefault(species(cat[i][1]), []).append(i)

    # The score estimate ignores rng/hard bonus photos even when the seed has
    # them, so their ids must not contribute a bonus here either.
    excluded = set(L.RNG_LOCATIONS) | set(L.HARD_LOCATIONS)
    skip = sorted(i for i, (c, n) in cat.items()
                  if i < 1000 and c in ("WONDERFUL_PHOTO", "MULTIPLE_PHOTO")
                  and n in excluded)

    lines = [
        "-- Generated by tools/make_oak_mapping.py -- do not edit by hand.",
        f"-- Built from apworld world_version {version}.",
        "--",
        "-- OAK_PHOTO_IDS  every base photo location, one per entry, which is",
        "--                exactly the list AtLeast() counts for the photo checks.",
        "-- OAK_SPECIES    those ids grouped by species; the report score takes the",
        "--                best course per species instead of adding them together.",
        "-- OAK_NO_BONUS   wonderful/multiple ids the score estimate always ignores",
        "--                because they are rng or hard photos.",
        "",
        "OAK_PHOTO_IDS = {" + ", ".join(str(i) for i in base) + "}",
        "",
        "OAK_SPECIES = {",
    ]
    for name, ids in groups.items():
        lines.append("    {%s},%s" % (", ".join(str(i) for i in ids),
                                      "" if len(ids) == 1 else "   -- " + name))
    lines += ["}", "", "OAK_NO_BONUS = {"]
    for i in skip:
        lines.append("    [%d] = true,   -- %s" % (i, cat[i][1]))
    lines += ["}", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    multi = sum(1 for v in groups.values() if len(v) > 1)
    print(f"wrote {OUT.relative_to(PACK).as_posix()}")
    print(f"  {len(base)} base photos, {len(groups)} species "
          f"({multi} spanning more than one course), {len(skip)} bonus ids ignored")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
